spring.application.name=clearing-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/ClearingDB
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

integrations.paymentProcessing.baseUrl=http://localhost:8081
integrations.paymentProcessing.connectTimeoutMs=2000
integrations.paymentProcessing.readTimeoutMs=4000
