server.port=8081
spring.application.name=payment-processing-service

# Configuración BD (Ajusta con tus credenciales locales o de Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/PaymentProcessingDB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.ecusol=INFO