server.port=8081
spring.application.name=payment-processing-service

# Configuracion BD (Ajusta con tus credenciales locales o de Docker)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:PaymentProcessingDB}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.payment=INFO

# URLs de servicios externos
network.service.url=${NETWORK_SERVICE_URL:http://localhost:8082}
balance.service.url=${BALANCE_SERVICE_URL:http://localhost:8083}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8086}
error.mapping.url=${ERROR_MAPPING_URL:http://localhost:8087}