spring.application.name=return-management-service

server.port=8085

# Base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/ReturnManagementDB
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Integración con Payment Processing
integrations.paymentProcessing.baseUrl=${PAYMENT_SERVICE_URL:http://localhost:8081}
integrations.paymentProcessing.connectTimeoutMs=2000
integrations.paymentProcessing.readTimeoutMs=4000

# Reglas de devolución
return-rules.max-hours=48
return-rules.enforce-amount-match=true

# Logging
logging.level.com.transswitch.returnmanagementservice=INFO
